### ISSUE TITLE
Render Frames but no gif created

### ISSUE THREAD

**Issue by Rusted-Iron** [doakey3/Bligify#19]
It renders the frames into a (project name)_folder but does not create a Gif file.

ive looked through the closed topics, and it seems to be an permissions problem, here the tings i´ve tried:

Reinstalled the addon
Gave Blender Administrator priviliges
rendered the gif to the desktop

General info:

i installed the master Branch
i use blender 2.83

it still does not convert to gif

no errors pop up as to my knowlege, though i did not check the console.

**Comment by cpmmckeown** [comment]
I am having the same issue

**Comment by robots-inc** [comment]
I am also having this issue with blender 2.83 and 2.9 alpha

**Comment by cpmmckeown** [comment]
*update - I wasn’t having any issues. I had downloaded the wrong folder for my system and was missing the two small programs that come bundled with the correct download. Make sure you have those .exe’s. If not, remove the add on from Blender, download the correct folder and start again. Great add on!

**Comment by DracoSeeker** [comment]
I had the same issue using Blender 2.83.4 on Linux Mint 20 Cinnamon.
It turns out my problem was that I used the browse-for-file option to point to where my ImageMagick file was and it somehow used a messed up file path.  I changed the path to the one I copied from the file manager and it worked perfectly.

**Comment by molton** [comment]
Thanks for making this.  I'm using Blender 2.8 in linux and I'm also having this problem.  I suspect it has to to with the dependencies, I manually select the paths and save the preferences, but when I come back into blender they're gone, that's not a good sign.  If i assign them while blender is running and do the process it looks like it works, it does the little calculation thing at the end, but no gif.  I installed ImageMagick-7.0.10-28 and gifsicle amd64 1.92-2   I see you updated this 2 months ago but I know how sometimes current versions of dependencies will cause issues.  Is that possibly the problem or am I just pointing to the wrong executable files?  if I use the which command it shows gifsicle in /usr/bin and imagemagick in /usr/local/bin. Blender makes me pick the exact exectuble and not enter a path and I noticed that the image and I noticed there's multiple image magic executables, should i pick the one that just says Magick?  Thanks again

I changed the path of gifsicle to /bin/gifsicle from /usr/bin/gifsicle and now I'm getting folders filled with pngs called gifname_frames and gifname_frames_frames.  I'm guessing the imagemagick path might be wrong too.  Also the path preference seems to be saved now so I guess that was just me or blender 2.80 or something.

**Comment by firatsoygul** [comment]
Images converted to gif are rendered incorrectly in ImageMagick version (6.9) installed from Ubuntu 20.04 official repository. We are getting the following error because these faulty gif files are not recognized by Gifsicle.

```
Combining GIF frames into animated GIF...
gifsicle:/<image_file_directory>//0001.gif: file not in GIF format
```

This problem seems to have been fixed in ImageMagick version 7.1. 
- Download the Appimage file of the latest version.
https://github.com/ImageMagick/ImageMagick/releases

- You can enter the full path of the file directly into the Magick Path field. 
- Or you can create a shortcut called magick under `/usr/bin`. You can leave the "magick path" field blank when you do this.

```
sudo ln -s /<appimage_file_directory>/ImageMagick-a454b3a-gcc-x86_64.AppImage /usr/bin/magick
```

It worked in conjunction with Ubuntu 20.04, Blender 2.93.4, ImageMagick 7.1.0-6 and Gifsicle 1.92.

**Comment by mohmehdi** [comment]
it also happens if output path contains a non English word in it .
gifsicle says Invalid argument

**Comment by nexxio** [comment]
I found a Fix!.. 
I had that problem and was because some permissions stuff that I still don't know. I'm using ubuntu 21.10 and blender 3.0.1. first I was using the flatpak version and because is sandboxed didn't have permissions to access "/run/user/1000/gvfs" and it didn't render anything. so I uninstalled the flatpak version and downloaded official blender from blender.org, then I started to get rendered the folder with the images and no .gif file. I was seeing the same error in the terminal of permission denied to use "/usr/bin/". so what I did was put the full path on the addon like: "/usr/bin/gifsicle" and "/usr/bin/convert" (that's the name of the executable for imagemagick in ubuntu since a few versions  ago). after that it worked nicely and rendered the .gif image. then I just saved the start up file so the paths don't reset when I close blender.
another thing that works to fix the problem (and is what I ended of choosing) is to download imagemagick appimage and putting it in your home folder and then adding that path in the addon for example: "/home/myuser/imagemagick/magick"

**Comment by mhmarf** [comment]
I also had this problem on Nobara 40. Solution was to download Blender directly from the website instead of using flatpak version...
Thank you for this addon!

**Comment by Andrematomer** [comment]
### Solution for GIF generation issues (UWP/Windows Store & Steam versions)

If you are using Blender from the **Windows Store (UWP)** or **Steam**, the add-on fails to automatically detect the paths for Gifsicle and ImageMagick because of how Windows sandboxes those folders. 

To fix this, you must manually set the paths in the add-on preferences:

1. Go to **Edit > Preferences > Add-ons** and find **Bligify**.
2. Expand the settings and locate the path fields for **Gifsicle** and **Magick (convert.exe)**.
3. Manually paste the following paths (replace `[Username]` and `[Version]` with your specific details):

**Gifsicle Path:**
`C:\Users\[Username]\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\[Version]\scripts\addons\bligify_windows\executables\gifsicle.exe`

**Magick (convert.exe) Path:**
`C:\Users\[Username]\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\[Version]\scripts\addons\bligify_windows\executables\convert.exe`

Once these are set, GIF generation should work correctly. Tested on Blender 5.0.1 (UWP version).
